<?php

namespace App\Models;

use CodeIgniter\Model;

class ProdutosModel extends Model 
{ 
    protected $db;

    protected $table = 'produtos';
    protected $primaryKey = "id";
    protected $useAutoIncrement = true;

    function __construct($group = 'default')
    {
        $this->db = \Config\Database::connect($group);
    }

    protected $allowedFields = [
        "id",
        "cod_produto",
        "sufixo",
        "creation_date",
        "last_update_date",
        "linha",
        "cod_linha",
        "desc_produto",
        "desc_formato_nominal",
        "desc_formato_real",
        "transpasse_maximo_madeiras",
        "lancamento",
        "cod_aplicacao_tecnica",
        "aplicacao_tecnica",
        "cor",
        "udm",
        "caracteristica_acabamento",
        "tipol_aba",
        "desc_tipologia_principal",
        "espessura",
        "qt_pc_m2",
        "qt_m2_caixa",
        "qt_pc_caixa",
        "qt_pc_camada",
        "qt_pc_pallet_mi",
        "qt_m2_pallet_mi",
        "qt_caixa_pallet_mi",
        "qt_peso_liquido",
        "qt_peso_bruto",
        "cod_variacao_tonalidade",
        "preco_peca",
        "valor_palete",
        "preco_caixa",
        "qtd_peso_liq_peca",
        "material",
        "uso",
        "residencial",
        "area_comercial_alto_trafego",
        "area_comercial_medio_trafego",
        "piscina",
        "areas_externas",
        "varandas_sacadas",
        "fachadas",
        "retro",
        "mosaico",
        "wallpaper",
        "tijolinho_pedras",
        "tecnica_design",
        "filetes_london",
        "extra_fino",
        "vidro_resina",
        "porcelana",
        "ceramicas",
        "metal",
        "piscina_interna",
        "piscina_borda",
        "piscina_area_externa",
        "cv_engenharia",
        "cv_revenda",
        "cv_portobello_shop",
        "cv_exportacao",
        "tags",
        "acabamento_de_borda",
        "junta_de_assentamento",
        "grupo",
        "epu",
        "resistencia_mecanica",
        "resistencia_a_abrasao_profunda",
        "res_abra_superficial",
        "expansao_por_umidade",
        "carga_ruptura",
        "agt_manch_verd_ol_leve",
        "agt_manch_verm_ol_leve",
        "iodo",
        "oleo",
        "absorcao_dagua",
        "acido_cloridrico_3",
        "acido_cloridrico_18",
        "hidroxido_de_potassio_30gl",
        "hidroxido_de_potássio_100gl",
        "acido_citrico_100gl",
        "acido_latico_5",
        "gretagem_port",
        "gretagem_ing",
        "congelamento_port",
        "congelamento_ing",
        "choque_termico_port",
        "choque_termico_ing",
        "atrito_seco_iso",
        "atrito_molhado_iso",
        "atrito_seco_astm",
        "atrito_molhado_astm",
        "absortancia",
        "cond_term_tabelaco",
        "calor_esp_tabelaco",
        "dens_apar_tabelaco",
        "emissiv_tabelaco",
        "absortancia_tabelaco",
        "transmit_tabelaco",
        "coef_alpha_tabelaco",
        "coef_ilumi_tabelaco",
        "impac_duro_tabelaco",
        "impac_mole_tabelaco",
        "resist_umid_tabelaco",
        "fv",
        "ranking",
        "selo",
        "categoria_site",
        "rejunte",
        "combina_com",
        "web_status",
        "normativa_15463",
        "normativa_13818",
        "normativa_15575",
        "normativa_13006",
        "normativa_10545",
        "normativa_na",
        "coef_expansao_term",
        "num_giros",
        "cloreto_amonia_100",
        "hipoclorito_sod_20",
        "ataque_qui_alta_conc",
        "ataque_qui_baixa_conc",
        "indice_rad_solar",
        "refletancia",
        "carga_concentrada",
        "ruido_impacto",
        "tipologia_comercial",
        "nr_faces",
        "atrito_pendulo",
        "color_body",
        "marca",
        "inventory_item_id",
        "deleted_mark",
        "indicacoes_uso",
        "origem",
        "fornecedor",
        "tipologia_cml",
        "class_portifolio",
        "class_port_n2",
        "class_port_n3",
        "class_port_n4",
        "descricao_longa",
        "cod_antigo",
        "cod_principal",
        "cv_porcelanateria",
        "cv_eng_varejo",
        "ean_cx",
        "ean_pc",
        "resultado_minimo_manchantes",
        "resultado_minimo_limpeza",
        "normativa_16928",
        "cv_pb_america",
        "junta_assentamento_is",
        "junta_assentamento_im",
        "junta_assentamento_ef",
        "junta_assentamento_p",
        "groupColor",
        "zoomImage",
        "enableforrevenda",
        "briefing"
    ];
    
    public function querySql($sql, $bindins) {
        return $this->db->query($sql, $bindins)->getResult();
    }

    public function truncateTable($sql) {
        return $this->db->query($sql);
    }
}